version: '2'

services:

  keycloak:
    extends:
        file: ./tools/docker/common-services.yml
        service: keycloak
    environment:
      CUSTOM_LOG_LEVEL: DEBUG
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,address=*:5005,suspend=n
    volumes:
      - ./src/main/resources/realms/demo-realm.json:/tmp/demo-realm.json
      - ./src/main/resources/cli:/opt/jboss/startup-scripts
    ports:
      - 9990:9990
      - 5005:5005
    depends_on:
      - smtp

  smtp:
    extends:
        file: ./tools/docker/common-services.yml
        service: smtp